# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      #      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: debug-statements
        exclude: '(batch|stream)?(.*)\.py'
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.0
  #   hooks:
  #     - id: prettier
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       name: python isort
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: python black
        exclude: '(batch|stream)?(.*)\.py'
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: python flake8
        exclude: '(batch|stream)?(.*)\.py'
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn", "--rcfile=pylintrc", "--fail-on=I"]
        # exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
      # - id: pylint
      #   name: python code
      #   entry: pylint --ignore=.conf
      #   language: system
      #   types: [python]
      #   args: ["-rn", "-sn", "--rcfile=.conf/pylintrc"]
