[tool.poetry]
name = "datathon-factored"
version = "0.1.0"
description = "This is the datathon project to build end-to-end project based on a data pipeline."
authors = ["Julio Cabrera <jcabrerahi@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "datathon_factored"}]

[tool.poetry.dependencies]
python = "^3.10"
azure-storage-file-datalake = "^12.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
