name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop*'

jobs:
  pre-commit-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies with Poetry
        run: poetry install --only dev

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files

      - name: Run pytest
        run: poetry run pytest --cov-report term-missing --cov=.
